FROM jboss/wildfly:9.0.1.Final

USER root
RUN yum -y install wget

USER jboss
WORKDIR $JBOSS_HOME

RUN wget -O ./standalone/deployments/jolokia.war http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/1.0.5/jolokia-war-1.0.5.war