FROM jboss/wildfly:10.1.0.Final

USER root
RUN yum -y install wget

USER jboss
WORKDIR $JBOSS_HOME

RUN wget -O ./standalone/deployments/jolokia.war http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/1.3.1/jolokia-war-1.3.1.war