FROM tomcat:8.5.28-jre8-alpine as tomcat-conf

FROM python:3.6.4 as alias-appender
COPY --from=tomcat-conf /usr/local/tomcat/conf/server.xml .
COPY add_hostname_alias .
ARG HOSTNAME=jolokia1.1.3-tomcat8.5.28-jre8-alpine
RUN ./add_hostname_alias

FROM tomcat:8.5.28-jre8-alpine

COPY --from=alias-appender ./server.xml conf/server.xml

RUN wget -O ./webapps/jolokia.war http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/1.1.3/jolokia-war-1.1.3.war