FROM jboss/wildfly:{{wildfly_version}}

USER root
RUN yum -y install wget

USER jboss
WORKDIR $JBOSS_HOME

RUN wget -O ./standalone/deployments/jolokia.war http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/{{jolokia_version}}/jolokia-war-{{jolokia_version}}.war
