#!/usr/bin/env python

from jinja2 import Environment, DictLoader, select_autoescape

import yaml

f = open('codeship-services.tmpl.yml', 'r')

services = f.read()
f.close()

env = Environment(
    loader=DictLoader({'codeship-services.yml': services})
)

template = env.get_template('codeship-services.yml')

with open('versions.yml', 'rb') as infile, open('codeship-services.yml', 'w') as outfile:
    versions = yaml.load(infile)

    for j in versions['jolokia']:
        for p in versions['python']:
            # for w in versions['app-servers']['wildfly']:
            #     context = {
            #         'python_version': p,
            #         'jolokia_agent_version': j['agent'],
            #         'jolokia_protocol_version': j['protocol'],
            #         'app_server': 'wildfly',
            #         'app_server_version': w
            #     }
            #     outfile.write(template.render(**context))

            for t in versions['app-servers']['tomcat']:
                context = {
                    'python_version': p,
                    'jolokia_agent_version': j['agent'],
                    'jolokia_protocol_version': j['protocol'],
                    'app_server': 'tomcat',
                    'app_server_version': t
                }
                outfile.write(template.render(**context))
