#!/usr/bin/env python

from jinja2 import Environment, FileSystemLoader
import yaml


with open('versions.yml', 'rb') as infile, open('codeship-services.yml', 'w') as outfile:
    versions = yaml.load(infile)

    env = Environment(
        loader=FileSystemLoader('./templates')
    )

    python_tmpl = env.get_template('python.tmpl.yml')
    jolokia_tmpl = env.get_template('jolokia.tmpl.yml')

    for j in versions['jolokia']:
        for t in versions['app-servers']['tomcat']:
            # for w in versions['app-servers']['wildfly']:
            #     context = {
            #         'python_version': p,
            #         'jolokia_agent_version': j['agent'],
            #         'jolokia_protocol_version': j['protocol'],
            #         'app_server': 'wildfly',
            #         'app_server_version': w
            #     }
            #     outfile.write(template.render(**context))

            context = {
                'jolokia_agent_version': j['agent'],
                'jolokia_protocol_version': j['protocol'],
                'app_server': 'tomcat',
                'app_server_version': t
            }

            outfile.write(jolokia_tmpl.render(**context))

            for p in versions['python']:
                context.update({'python_version': p})
                outfile.write(python_tmpl.render(**context))
