FROM tomcat:8.0.50-jre8-alpine as tomcat-conf

FROM python:3.6.4 as alias-appender
COPY --from=tomcat-conf /usr/local/tomcat/conf/server.xml .
COPY add_hostname_alias .
ARG HOSTNAME=jolokia1.2.1-tomcat8.0.50-jre8-alpine
RUN ./add_hostname_alias

FROM tomcat:8.0.50-jre8-alpine

COPY --from=alias-appender ./server.xml conf/server.xml

RUN wget -O ./webapps/jolokia.war http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/1.2.1/jolokia-war-1.2.1.war