FROM tomcat:8.0.50-jre7-alpine as tomcat-conf

FROM python:3.6.4 as alias-appender
COPY --from=tomcat-conf /usr/local/tomcat/conf/server.xml .
COPY add_hostname_alias .
ARG HOSTNAME=jolokia1.3.0-tomcat8.0.50-jre7-alpine
RUN ./add_hostname_alias

FROM tomcat:8.0.50-jre7-alpine

COPY --from=alias-appender ./server.xml conf/server.xml

RUN wget -O ./webapps/jolokia.war http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/1.3.0/jolokia-war-1.3.0.war