pipeline {
  agent none
  stages {
    stage('Test') {
      agent {
        docker {
          image 'python:3.6.4'
        }
      }
      steps {
        git url: 'https://github.com/wbrefvem/python-jolokia.git', branch: 'pipeline'
        sh 'pip install -r requirements.txt -r dev-requirements.txt'
        sh 'pytest -v --junit-xml test-reports/results.xml'
        junit 'test-reports/results.xml'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying'
      }
    }
  }
}