pipeline {
  agent none
  stages {
    stage('Test') {
      agent {
        docker {
          image: 'python:3.6.4'
        }
        
      }
      steps {
        container('python') {
          git url: 'https://github.com/wbrefvem/python-jolokia.git', branch: 'pipeline'
          sh 'pip install pipenv --upgrade'
          sh 'pipenv install --dev --deploy --system'
          sh 'pytest -v --junit-xml test-reports/results.xml'
          junit 'test-reports/results.xml'
        }
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying'
      }
    }
  }
}